content_validation:
  description: >
    Validate narrative quality, pace, fluency, engagement potential of the content.
    Provide actionable feedback and suggestions for improvement where necessary.   
  expected_output: >
    A ValidationReport containing detailed suggestions for improvement.
  agent: content_critic