content_validation:
  description: >
    Validate narrative quality, pace, fluency, engagement potential of the content.
    Provide actionable feedback and suggestions for improvement where necessary.

    Inputs:
    Script Output: {script_output}
    Visuals Output: {visuals_output}
    Target Audience: {target_audience}
    
  expected_output: >
    A ValidationReport containing detailed suggestions for improvement.
  agent: content_critic