generate_visuals:
  description: >
    Create visual prompts for each of the 3 script parts. Each part should have its own set of timestamped descriptions, 
    visual compositions, and stylistic preferences.
    The visuals should reflect the interests and preferences of the target audience.  
  expected_output: >
    A VisualPromptSeries containing 3 VisualPromptSet (one per script part).
  agent: visual_artist